### ISSUE TITLE
failed to download sometimes in QQ music playlist download

### ISSUE THREAD

**Issue by MrWilliamJackson** [Beadd/MusicDownloader#14]
When downloading [神のまにまに](https://y.qq.com/n/ryqq/songDetail/004JJt594ga4KU) in a playlist :

```
--------------------------------------------------
13 神のまにまに  4042699字节
Traceback (most recent call last):
  File "MusicDownloader.py", line 291, in <module>
    if Music() == 0:
  File "MusicDownloader.py", line 152, in Music
    audiofile.tag.images.set(3, audio_Image.content, "image/jpeg")
  File "eyed3\utils\__init__.py", line 143, in wrapped_fn
  File "eyed3\id3\tag.py", line 1593, in set
ValueError: img_url MUST not be none when no image data
[17956] Failed to execute script 'MusicDownloader' due to unhandled exception!
  已内嵌名称  已内嵌歌手
[已退出进程，代码为 1 (0x00000001)]
```

----

Downloading [花降らし](https://y.qq.com/n/ryqq/songDetail/0000Rjrl2iyqY5)  :

```
28 花降らし  4719789字节
Traceback (most recent call last):
  File "MusicDownloader.py", line 291, in <module>
    if Music() == 0:
  File "MusicDownloader.py", line 152, in Music
    audiofile.tag.images.set(3, audio_Image.content, "image/jpeg")
  File "eyed3\utils\__init__.py", line 143, in wrapped_fn
  File "eyed3\id3\tag.py", line 1593, in set
ValueError: img_url MUST not be none when no image data
[5604] Failed to execute script 'MusicDownloader' due to unhandled exception!
  已内嵌名称  已内嵌歌手
[已退出进程，代码为 1 (0x00000001)]
```

It is worth noting that, the problem doesn't happen to any specific songs or playlists.
Also it connot download QQ music vip songs at the moment

**Comment by Beadd** [comment]
> When downloading [神のまにまに](https://y.qq.com/n/ryqq/songDetail/004JJt594ga4KU) in a playlist :
> 
> ```
> --------------------------------------------------
> 13 神のまにまに  4042699字节
> Traceback (most recent call last):
>   File "MusicDownloader.py", line 291, in <module>
>     if Music() == 0:
>   File "MusicDownloader.py", line 152, in Music
>     audiofile.tag.images.set(3, audio_Image.content, "image/jpeg")
>   File "eyed3\utils\__init__.py", line 143, in wrapped_fn
>   File "eyed3\id3\tag.py", line 1593, in set
> ValueError: img_url MUST not be none when no image data
> [17956] Failed to execute script 'MusicDownloader' due to unhandled exception!
>   已内嵌名称  已内嵌歌手
> [已退出进程，代码为 1 (0x00000001)]
> ```
> 
> Downloading [花降らし](https://y.qq.com/n/ryqq/songDetail/0000Rjrl2iyqY5) :
> 
> ```
> 28 花降らし  4719789字节
> Traceback (most recent call last):
>   File "MusicDownloader.py", line 291, in <module>
>     if Music() == 0:
>   File "MusicDownloader.py", line 152, in Music
>     audiofile.tag.images.set(3, audio_Image.content, "image/jpeg")
>   File "eyed3\utils\__init__.py", line 143, in wrapped_fn
>   File "eyed3\id3\tag.py", line 1593, in set
> ValueError: img_url MUST not be none when no image data
> [5604] Failed to execute script 'MusicDownloader' due to unhandled exception!
>   已内嵌名称  已内嵌歌手
> [已退出进程，代码为 1 (0x00000001)]
> ```
> 
> It is worth noting that, the problem doesn't happen to any specific songs or playlists. Also it connot download QQ music vip songs at the moment

第一首可以下载，第二首歌的封面出错了，已经修复

**Comment by Beadd** [comment]
见v1.8.4
