### ISSUE TITLE
vip 歌曲的URL 打不开了是怎么回事？

### ISSUE THREAD

**Issue by GryllusGit** [Beadd/MusicDownloader#17]
比如这个："url": "https://api.injahow.cn/meting/?server=tencent&type=url&id=001EicO642B91t",

**Comment by GryllusGit** [comment]
不对吧。mode=3,就是 qq 单曲哦。
并且网易云的 vip 曲目也不能通了。

**Comment by Beadd** [comment]
这个API出问题了,突然无法解析了

**Comment by GryllusGit** [comment]
api 什么时候能恢复？

**Comment by Beadd** [comment]
> api 什么时候能恢复？

API用的是 @injahow /[meting-api](https://github.com/injahow/meting-api)，并不清楚
