### ISSUE TITLE
重复下载里跳过已下载的文件

### ISSUE THREAD

**Issue by yuzifu** [Beadd/MusicDownloader#18]
感谢作者！
在使用的过程发现，程序在下载时有时会闪退，再次下载时不会跳过已下载的文件，期待加入跳过已下载文件。

**Comment by Beadd** [comment]
> 

OK，已经添加跳过已下载文件功能，过几天放[Releases](https://github.com/Beadd/MusicDownloader/releases)

**Comment by Graundcian** [comment]
请问，可以下载无损吗？

**Comment by Beadd** [comment]
> 请问，可以下载无损吗？

暂时还没发现这个API有下载无损的功能
