### ISSUE TITLE
qq 音乐解析错误?

### ISSUE THREAD

**Issue by liudonghua123** [Beadd/MusicDownloader#20]
![image](https://user-images.githubusercontent.com/2276718/207834461-134452f9-db7b-4127-bd12-a168e1c6be90.png)

例如 https://y.qq.com/n/ryqq/songDetail/003AC4Vq2gG1XN 这一首歌, 歌曲 ID 不是 003AC4Vq2gG1XN 么?

另外歌单下载的时候还提示输入单曲id, 还不支持歌单下载么, 例如 https://y.qq.com/n/ryqq/playlist/8710032158

**Comment by liudonghua123** [comment]
我之前也写过一个下载qq音乐的, 不过是使用 playwright , 不过还是不能下载完整的 vip 歌曲
https://github.com/liudonghua123/music_downloader/blob/main/main.py

**Comment by Beadd** [comment]
> ![image](https://user-images.githubusercontent.com/2276718/207834461-134452f9-db7b-4127-bd12-a168e1c6be90.png)
> 
> 例如 https://y.qq.com/n/ryqq/songDetail/003AC4Vq2gG1XN 这一首歌, 歌曲 ID 不是 003AC4Vq2gG1XN 么?
> 
> 另外歌单下载的时候还提示输入单曲id, 还不支持歌单下载么, 例如 https://y.qq.com/n/ryqq/playlist/8710032158

测试可以下载，图片里的问题是：QQ单曲下载选3，歌单下载选4

**Comment by Beadd** [comment]
唔……还未找到能解析VIP歌曲的API
