### ISSUE TITLE
使用pip安装的怎么用？

### ISSUE THREAD

**Issue by martjay** [Beadd/MusicDownloader#21]
我用你的exe到粘贴链接回车闪退

pip安装的要怎么下载，使用什么语法？

**Comment by Beadd** [comment]
> 我用你的exe到粘贴链接回车闪退
> 
> pip安装的要怎么下载，使用什么语法？

下载python，添加环境变量之后在命令行输入
`pip install requests`
`pip install eyeD3`
安装完成后使用python打开musicdownloader.py即可

**Comment by Beadd** [comment]
闪退可能是没有关闭梯子类的东西

**Comment by martjay** [comment]
> > 我用你的exe到粘贴链接回车闪退
> > pip安装的要怎么下载，使用什么语法？
> 
> 下载python，添加环境变量之后在命令行输入 `pip install requests` `pip install eyeD3` 安装完成后使用python打开musicdownloader.py即可

用了新版，确实可以下载了谢谢咯，但是会有一些提示“你大概是没登陆或者缺少钞能力”，如果能破就好了
