### ISSUE TITLE
有两个小问题，看看能不能解决，封面和码率

### ISSUE THREAD

**Issue by JJBoomShaKa** [Beadd/MusicDownloader#22]
网易云，内嵌的封面太过模糊，下载的音乐码率略低（大部分为128k的）

**Comment by Beadd** [comment]
解决了封面模糊问题，见[v1.9.1](https://github.com/Beadd/MusicDownloader/releases/tag/v1.9.1)

**Comment by JJBoomShaKa** [comment]
感谢作者及时更新，已试用v1.9.1，问题未完全解决。
网易云
1. 单曲下载封面模糊已解决，歌单下载封面依旧模糊。
2. 在更改“歌曲下载项设置”中，将“歌曲是否下载歌词”改为“False”，此时进行下载网易云歌单时，第二首歌程序就会自动闪退。（已尝试多个歌单）

**Comment by Beadd** [comment]
感谢你的测试，修复了“歌曲是否下载歌词”选项的BUG，也将高清封面应用到了歌单下载，见[v1.9.2](https://github.com/Beadd/MusicDownloader/releases/tag/v1.9.2)
