### ISSUE TITLE
song name too long 

### ISSUE THREAD

**Issue by Windy147** [Beadd/MusicDownloader#24]
OSError: [Errno 36] File name too long:              version:1.9.2

by the way,v1.9.3 often breakdown.
'AttributeError: 'Tag' object has no attribute 'copyright'. Did you mean: 'copyright_url'?'

感谢你的开源项目，真实帮了大忙。

**Comment by Beadd** [comment]
可以试试最新版[v2.0.0](https://github.com/Beadd/MusicDownloader/releases/tag/v2.0.0)
