### ISSUE TITLE
下载到某一首歌就卡住不动的情况。

### ISSUE THREAD

**Issue by cenzijing** [Beadd/MusicDownloader#26]
有时下载的文件夹中会出现歌名之后有（1）的文件，当这个文件出现并且再次下载到这首歌的时候，程序无法检测已经下载过这首歌，并且会在此处卡住，无法继续运行。

**Comment by Beadd** [comment]
已修复，见[v2.0.2](https://github.com/Beadd/MusicDownloader/releases/tag/v2.0.2)

**Comment by Linon419** [comment]
> 已修复，见[v2.0.2](https://github.com/Beadd/MusicDownloader/releases/tag/v2.0.2)

还是不行，下载到第三首歌就不行了 网易云歌单id：521806549

**Comment by Beadd** [comment]
> > 已修复，见[v2.0.2](https://github.com/Beadd/MusicDownloader/releases/tag/v2.0.2)
> 
> 还是不行，下载到第三首歌就不行了 网易云歌单id：521806549

测试没有问题，可以下载差不多一百多首的歌曲，只是每天的API调用次数有限制
