### ISSUE TITLE
能不能加两个小功能，直接通过链接识别ID，和文件名一定程度的自定义

### ISSUE THREAD

**Issue by qhfg** [Beadd/MusicDownloader#30]
1、直接通过链接识别ID（主要嫌复制分享链接出去再复制ID回来有点麻烦）
2、保存时的文件名一定程度的自定义（比如我喜欢 “歌手名 - 歌曲名.mp3”）

**Comment by Beadd** [comment]
已更新，见[v2.1.0](https://github.com/Beadd/MusicDownloader/releases/tag/v2.1.0)
