### ISSUE TITLE
增加GUI

### ISSUE THREAD

**Issue by ZYKsslm** [Beadd/MusicDownloader#33]
希望能写一个GUI

**Comment by cyh1998** [comment]
@Beadd 考虑建个分支吗？

**Comment by ZYKsslm** [comment]
> @Beadd 考虑建个分支吗？

你可以pr一下😏

**Comment by cyh1998** [comment]
> > @Beadd 考虑建个分支吗？
> 
> 你可以pr一下😏

不知道原作者有没有做GUI的意愿，有的话我可以pr下

**Comment by cyh1998** [comment]
@ZYKsslm 可以先体验下
https://github.com/cyh1998/MusicDownloader/tree/dev-GUI

**Comment by Beadd** [comment]
> @ZYKsslm 可以先体验下 https://github.com/cyh1998/MusicDownloader/tree/dev-GUI

pr的话我会用这个发3.0版本
