### ISSUE TITLE
网易云音乐歌单获取报错

### ISSUE THREAD

**Issue by SuperDannyBoy** [Beadd/MusicDownloader#34]
![QQ截图20230514104606](https://github.com/Beadd/MusicDownloader/assets/5237197/1f979ff2-785f-4339-9892-b5050b9d7404)

**Comment by Beadd** [comment]
> ![QQ截图20230514104606](https://user-images.githubusercontent.com/5237197/238164866-1f979ff2-785f-4339-9892-b5050b9d7404.png)

具体是哪个歌单呢？

**Comment by SuperDannyBoy** [comment]
> > ![QQ截图20230514104606](https://user-images.githubusercontent.com/5237197/238164866-1f979ff2-785f-4339-9892-b5050b9d7404.png)
> 
> 具体是哪个歌曲单呢，能不能提供一下id？

523615729

**Comment by Beadd** [comment]
> > > ![QQ截图20230514104606](https://user-images.githubusercontent.com/5237197/238164866-1f979ff2-785f-4339-9892-b5050b9d7404.png)
> > 
> > 
> > 具体是哪个歌曲单呢，能不能提供一下id？
> 
> 523615729

亲测没有问题，可以下载里面37首非VIP歌曲。你可以看看是否选择的是第二个选项（网易云歌单下载），或者今天请求次数太多，可以等明天再试

**Comment by SuperDannyBoy** [comment]
> > > > ![QQ截图20230514104606](https://user-images.githubusercontent.com/5237197/238164866-1f979ff2-785f-4339-9892-b5050b9d7404.png)
> > > 
> > > 
> > > 具体是哪个歌曲单呢，能不能提供一下id？
> > 
> > 
> > 523615729
> 
> 亲测没有问题，可以下载里面37首非VIP歌曲。你可以看看是否选择的是第二个选项（网易云歌单下载），或者今天请求次数太多，可以等明天再试

那应该就是了，今天获取了将近一千首歌。另外请教下大佬，VIP或者置灰的歌曲是否有另外的方式获取？

**Comment by Beadd** [comment]
> > > > > ![QQ截图20230514104606](https://user-images.githubusercontent.com/5237197/238164866-1f979ff2-785f-4339-9892-b5050b9d7404.png)
> > > > 
> > > > 
> > > > 具体是哪个歌曲单呢，能不能提供一下id？
> > > 
> > > 
> > > 523615729
> > 
> > 
> > 亲测没有问题，可以下载里面37首非VIP歌曲。你可以看看是否选择的是第二个选项（网易云歌单下载），或者今天请求次数太多，可以等明天再试
> 
> 那应该就是了，今天获取了将近一千首歌。另外请教下大佬，VIP或者置灰的歌曲是否有另外的方式获取？

方法暂无，一般都是替换音源到其他平台下载
