### ISSUE TITLE
音乐名称解析错误

### ISSUE THREAD

**Issue by SuperDannyBoy** [Beadd/MusicDownloader#35]
![image](https://github.com/Beadd/MusicDownloader/assets/5237197/db542619-42e7-4e13-9421-762b439bcfcc)
该音乐完整名称：
![image](https://github.com/Beadd/MusicDownloader/assets/5237197/c5ca7392-0333-40c4-93d8-1979917e4ef4)

**Comment by Beadd** [comment]
已修复，见[v2.2.1](https://github.com/Beadd/MusicDownloader/releases/tag/v2.2.1)
