### ISSUE TITLE
使用exe下载歌单会出现自动闪退

### ISSUE THREAD

**Issue by 908566141** [Beadd/MusicDownloader#36]
如题，在win11平台使用此程序下载网易云歌单时会出现下载了几首歌就闪退的情况

**Comment by Beadd** [comment]
具体是哪个歌单呢？

**Comment by 908566141** [comment]
> 具体是哪个歌单呢？

https://y.music.163.com/m/playlist?id=8279713301&userid=1401107650&creatorId=1401107650

**Comment by Beadd** [comment]
> > 具体是哪个歌单呢？
> 
> https://y.music.163.com/m/playlist?id=8279713301&userid=1401107650&creatorId=1401107650

实测能下载574首，因为有频率限制，你可以自建[API服务器](https://github.com/injahow/meting-api)或者等明天再下

**Comment by 908566141** [comment]
> > > 具体是哪个歌单呢？
> > 
> > 
> > https://y.music.163.com/m/playlist?id=8279713301&userid=1401107650&creatorId=1401107650
> 
> 实测能下载574首，因为有频率限制，你可以自建[API服务器](https://github.com/injahow/meting-api)或者等明天再下

所以这是api服务器的频率限制哈，那我明天试试
