### ISSUE TITLE
可以添加歌曲发行的年份吗?

### ISSUE THREAD

**Issue by jsjcjsjc** [Beadd/MusicDownloader#38]
感谢~~

**Comment by Beadd** [comment]
添加了，见[v2.3.2](https://github.com/Beadd/MusicDownloader/releases/tag/v2.3.2)

**Comment by jsjcjsjc** [comment]
> 添加了，见[v2.3.2](https://github.com/Beadd/MusicDownloader/releases/tag/v2.3.2)

感谢, 但是似乎QQ音乐没有年份?只有网易云既有年份又可以专辑等信息?

**Comment by Beadd** [comment]
添加了，见[v2.5.0](https://github.com/Beadd/MusicDownloader/releases/tag/v2.5.0)

**Comment by jsjcjsjc** [comment]
你这服务比收费软件都强哈~~~贴个咖啡二维码吧~~

**Comment by Beadd** [comment]
![](https://raw.githubusercontent.com/Beadd/MusicDownloader/main/coffee.png)
感谢~

**Comment by jsjcjsjc** [comment]
> ![](https://raw.githubusercontent.com/Beadd/MusicDownloader/main/coffee.png) 感谢~

ok,已转,直接贴首页哈,哈哈

**Comment by Beadd** [comment]
非常感谢

**Comment by jsjcjsjc** [comment]
> 非常感谢

测试了一下,还是没有年份哈,测试歌单->https://y.qq.com/n/ryqq/playlist/8910251849

**Comment by Beadd** [comment]
> > 非常感谢
> 
> 测试了一下,还是没有年份哈,测试歌单->https://y.qq.com/n/ryqq/playlist/8910251849

已修复，见[v2.5.1](https://github.com/Beadd/MusicDownloader/releases/tag/v2.5.1)
