### ISSUE TITLE
hope artist /album id supported.

### ISSUE THREAD

**Issue by GryllusGit** [Beadd/MusicDownloader#4]
hope artist ,album id supported.
and files can be stored in separate folder may be better?
thx a lot.

**Comment by Beadd** [comment]
OK!

**Comment by Beadd** [comment]
> hope artist ,album id supported. and files can be stored in separate folder may be better? thx a lot.

OK!

**Comment by Beadd** [comment]
添加了专辑下载，如果失效请更换COOKIE

**Comment by Beadd** [comment]
想更改下载目录可以改源文件开头的全局变量MusicDirName和LyricDirName
