### ISSUE TITLE
vip 的下载下来都是30s怎么办

### ISSUE THREAD

**Issue by GryllusGit** [Beadd/MusicDownloader#40]

**Comment by Beadd** [comment]
这个API并不支持解析会员歌曲

**Comment by jsjcjsjc** [comment]
> 

大佬部署过API吗,我自己想部署个收费歌曲API...但是按照https://github.com/injahow/meting-api部署完以后,就不知道下一步了~~
找了一圈也没有找到github.com/injahow/meting-api的部署教程哈~~

**Comment by Beadd** [comment]
> > 
> 
> 大佬部署过API吗,我自己想部署个收费歌曲API...但是按照[https://github.com/injahow/meting-api部署完以后,就不知道下一步了](https://github.com/injahow/meting-api%E9%83%A8%E7%BD%B2%E5%AE%8C%E4%BB%A5%E5%90%8E,%E5%B0%B1%E4%B8%8D%E7%9F%A5%E9%81%93%E4%B8%8B%E4%B8%80%E6%AD%A5%E4%BA%86)~~ 找了一圈也没有找到github.com/injahow/meting-api的部署教程哈~~

```
sudo apt install php 
```
```
cd /var/www/html/
```
```
sudo rm ./index.html
```
```
git clone https://github.com/injahow/meting-api.git
```
```
sudo mv meting-api/* ./
```
```
sudo apt install composer
```
```
sudo apt install php-curl
```
```
composer install
```
这是在ubuntu上部署的全部指令，但无法解析VIP歌曲

**Comment by Beadd** [comment]
> > > > 
> > > 
> > > 
> > > 大佬部署过API吗,我自己想部署个收费歌曲API...但是按照[https://github.com/injahow/meting-api部署完以后,就不知道下一步了](https://github.com/injahow/meting-api%E9%83%A8%E7%BD%B2%E5%AE%8C%E4%BB%A5%E5%90%8E,%E5%B0%B1%E4%B8%8D%E7%9F%A5%E9%81%93%E4%B8%8B%E4%B8%80%E6%AD%A5%E4%BA%86)~~ 找了一圈也没有找到github.com/injahow/meting-api的部署教程哈~~
> > 
> > 
> > ```
> > sudo apt install php 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > cd /var/www/html/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > sudo rm ./index.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > git clone https://github.com/injahow/meting-api.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > sudo mv meting-api/* ./
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > sudo apt install composer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > sudo apt install php-curl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > composer install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是在ubuntu上部署的全部指令，但无法解析VIP歌曲
> 
> 感谢,我也搭建OK了,解析VIP歌曲有啥办法吗? 我已经是QQ和我网易的会员了

暂无

**Comment by jsjcjsjc** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 大佬部署过API吗,我自己想部署个收费歌曲API...但是按照[https://github.com/injahow/meting-api部署完以后,就不知道下一步了](https://github.com/injahow/meting-api%E9%83%A8%E7%BD%B2%E5%AE%8C%E4%BB%A5%E5%90%8E,%E5%B0%B1%E4%B8%8D%E7%9F%A5%E9%81%93%E4%B8%8B%E4%B8%80%E6%AD%A5%E4%BA%86)~~ 找了一圈也没有找到github.com/injahow/meting-api的部署教程哈~~
> > > 
> > > 
> > > ```
> > > sudo apt install php 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > cd /var/www/html/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > sudo rm ./index.html
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > git clone https://github.com/injahow/meting-api.git
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > sudo mv meting-api/* ./
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > sudo apt install composer
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > sudo apt install php-curl
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > composer install
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这是在ubuntu上部署的全部指令，但无法解析VIP歌曲
> > 
> > 
> > 感谢,我也搭建OK了,解析VIP歌曲有啥办法吗? 我已经是QQ和我网易的会员了
> 
> 暂无

啊,大佬拿你提到的VIP歌曲取决于API, 但其实目前也没有VIP歌曲的办法吗~~

**Comment by Beadd** [comment]
> 

以前这个API是可以解析VIP歌曲的，API服务器里添加会员COOKIE理论上是可以解析会员歌曲的

**Comment by jsjcjsjc** [comment]
> > 
> 
> 以前这个API是可以解析VIP歌曲的，API服务器里添加会员COOKIE理论上是可以解析会员歌曲的

大佬有尝试添加会员cookie吗? 我看这个API的说明很简单,不知道咋添加哈~~

**Comment by Beadd** [comment]
> > > 
> > 
> > 
> > 以前这个API是可以解析VIP歌曲的，API服务器里添加会员COOKIE理论上是可以解析会员歌曲的
> 
> 大佬有尝试添加会员cookie吗? 我看这个API的说明很简单,不知道咋添加哈~~

https://github.com/injahow/meting-api/blob/2b7b96c9b55e5dfdd99ff7a0a8adeb7560bb07aa/index.php#L54-L58
设置你自己的会员cookie即可解析会员歌曲

**Comment by jsjcjsjc** [comment]
> > > > 
> > > 
> > > 
> > > 以前这个API是可以解析VIP歌曲的，API服务器里添加会员COOKIE理论上是可以解析会员歌曲的
> > 
> > 
> > 大佬有尝试添加会员cookie吗? 我看这个API的说明很简单,不知道咋添加哈~~
> 
> https://github.com/injahow/meting-api/blob/2b7b96c9b55e5dfdd99ff7a0a8adeb7560bb07aa/index.php#L54-L58 设置你自己的会员cookie即可解析会员歌曲

感谢,搞定了
