### ISSUE TITLE
歌曲下载不完整及功能建议

### ISSUE THREAD

**Issue by Guovin** [Beadd/MusicDownloader#42]
1.出现大量短时间的歌曲，1分钟以内（貌似是vip？），建议增加过滤此类歌曲功能。
2.音乐与歌词文件数量不一致，可能有部分纯音乐无歌词文件？建议手动删除音乐文件后，执行命令能同时删除对应歌词文件。
3.建议增加导出未下载成功、跳过、过滤部分歌曲名单txt文件。

**Comment by Beadd** [comment]
1. vip歌曲突然能解析30秒了，解析的内容和正常歌曲一样，无法过滤
2. 其实歌词文件已经内嵌歌曲里了，你可以在设置里取消下载歌词，这个API服务每天有限制，一千首差不多，你可以自建API服务或者等下一天

**Comment by Beadd** [comment]
添加了日志，见[v2.4.0](https://github.com/Beadd/MusicDownloader/releases/tag/v2.4.0)
