### ISSUE TITLE
QQ会员歌曲下载

### ISSUE THREAD

**Issue by Beadd** [Beadd/MusicDownloader#44]
_Originally posted by @jsjcjsjc in https://github.com/Beadd/MusicDownloader/issues/38#issuecomment-1575428830_

**Comment by Beadd** [comment]
https://github.com/injahow/meting-api/blob/230e38df9aff90e41d02e9bdeec5f0c866764ac7/src/Meting.php#L874
同样在这里添加QQ会员Cookie既可解析会员歌曲

**Comment by Beadd** [comment]
https://github.com/injahow/meting-api/blob/2b7b96c9b55e5dfdd99ff7a0a8adeb7560bb07aa/src/Meting.php#L642
将br参数旁的1000修改为10000或更大即可做到无损

**Comment by jsjcjsjc** [comment]
我测试了一下，大部分的歌曲ok，VIP歌曲也OK，但是部分独占VIP歌曲不行吗？比如这个歌单https://y.qq.com/n/ryqq/playlist/8917587841

大佬有条件测试吗？

**Comment by jsjcjsjc** [comment]
测试了一下
网易测试歌单,加入vipc ookie后有些VIP可以下,有些不行
https://music.163.com/playlist?id=8454523851
QQ歌单,加入vipc ookie后有些VIP可以下,有些不行,这里的都不能下
https://y.qq.com/n/ryqq/playlist/8917587841

估计是API问题~~我去那边问问

**Comment by Beadd** [comment]
> 我测试了一下，大部分的歌曲ok，VIP歌曲也OK，但是部分独占VIP歌曲不行吗？比如这个歌单https://y.qq.com/n/ryqq/playlist/8917587841
> 
> 大佬有条件测试吗？

可能是因为服务器那里QQ的cookie没及时更换，实测可以下载

**Comment by Beadd** [comment]
> 测试了一下 网易测试歌单,加入vipc ookie后有些VIP可以下,有些不行 https://music.163.com/playlist?id=8454523851 QQ歌单,加入vipc ookie后有些VIP可以下,有些不行,这里的都不能下 https://y.qq.com/n/ryqq/playlist/8917587841
> 
> 估计是API问题~~我去那边问问

已添加网易云无损下载，见[v2.6.0](https://github.com/Beadd/MusicDownloader/releases/tag/v2.6.0)
