### ISSUE TITLE
QQ音乐下载提示ID有误

### ISSUE THREAD

**Issue by RouJiANG-14** [Beadd/MusicDownloader#5]
难道不是分享页面
 https://i.y.qq.com/v8/playsong.html?songid=339347269
的这个ID么？？

**Comment by Beadd** [comment]
是歌曲页面链接上每首歌曲不一样的地方
> ![](https://raw.githubusercontent.com/Beadd/MusicDownloader/main/QQmusicID.png)
> 像这个的ID为003eZ03f3yrLl5

**Comment by Beadd** [comment]
> 难道不是分享页面 https://i.y.qq.com/v8/playsong.html?songid=339347269 的这个ID么？？

是歌曲页面链接上每首歌曲不一样的地方
> ![](https://raw.githubusercontent.com/Beadd/MusicDownloader/main/QQmusicID.png)
> 像这个的ID为003eZ03f3yrLl5

**Comment by Beadd** [comment]
> 难道不是分享页面 https://i.y.qq.com/v8/playsong.html?songid=339347269 的这个ID么？？

你那首歌的ID是001Pet2M1H10Hl

**Comment by Beadd** [comment]
ID检查有误,我写快大意了

**Comment by Beadd** [comment]
> 难道不是分享页面 https://i.y.qq.com/v8/playsong.html?songid=339347269 的这个ID么？？

这首歌的ID是001Pet2M1H10Hl

**Comment by Beadd** [comment]
> > 难道不是分享页面 https://i.y.qq.com/v8/playsong.html?songid=339347269 的这个ID么？？
> 
> 这首歌的ID是001Pet2M1H10Hl
> 原链接https://y.qq.com/n/ryqq/songDetail/001Pet2M1H10Hl

**Comment by RouJiANG-14** [comment]
用最新的解决了，另外不能开代理的事情忘了，怪不得一直报错！感激大佬！
