### ISSUE TITLE
[Bug] 下载歌曲Can't Hold Us解析不出music_type

### ISSUE THREAD

**Issue by LuckyXixi** [Beadd/MusicDownloader#51]
File "/MusicDownloader/musicdownloader.py", line 155, in name_get_music_path
    music_path = g_music_dir_name + '/' + name + '.' + music_type
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

Debug 查看到redirect url为https://m7.music.126.net/20230623182314/b582e34c8a66f725348033832ae8065b/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/11406982739/89f9/90c7/a204/c8789cd036a18285e36d1c7cbbca704a.

**Comment by Beadd** [comment]
> File "/MusicDownloader/musicdownloader.py", line 155, in name_get_music_path music_path = g_music_dir_name + '/' + name + '.' + music_type ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~ TypeError: can only concatenate str (not "NoneType") to str
> 
> Debug 查看到redirect url为https://m7.music.126.net/20230623182314/b582e34c8a66f725348033832ae8065b/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/11406982739/89f9/90c7/a204/c8789cd036a18285e36d1c7cbbca704a.

刚测试没有问题，能提供歌曲的ID吗

**Comment by LuckyXixi** [comment]
https://music.163.com/#/song?id=27942090

**Comment by LuckyXixi** [comment]
由于music_type是解析句点后面的部分，该redirect url句点后为空，因此函数返回NoneType，在连接字符串时报错

**Comment by Beadd** [comment]
> https://music.163.com/#/song?id=27942090

测试可以下载。
你可以检查你填入的API是否能解析此音乐，API服务器是否添加了会员COOKIE
http://API服务器/meting-api/?type=song&id=27942090

**Comment by LuckyXixi** [comment]
哦哦，我没有会员，这种情况下应该就解析不了了，但解析的链接也是可以播放的片段。

**Comment by Beadd** [comment]
已修复，见[v2.6.1](https://github.com/Beadd/MusicDownloader/releases/tag/v2.6.1)
