### ISSUE TITLE
qq音乐歌曲原始ID哪里获取

### ISSUE THREAD

**Issue by yehonghao** [Beadd/MusicDownloader#55]
大佬你好，用qq音乐用分享连接里的id无法下载，https://i.y.qq.com/v8/playsong.html?songid=339347269
2.1版本支持 添加功能：直接通过链接识别ID 是支持这个id么。
或者有其它方式获取001Pet2M1H10Hl这种原始ID么？
![image](https://github.com/Beadd/MusicDownloader/assets/16252285/4221b767-297c-47a4-b1ba-e70e0a7d2fa5)

**Comment by Beadd** [comment]
受API服务限制，无法解析分享链接里的（点击播放，在播放界面再点击歌曲名就可以获得实际ID）

**Comment by yehonghao** [comment]
好的，多谢
