### ISSUE TITLE
MP3Tag 编辑功能

### ISSUE THREAD

**Issue by htname** [Beadd/MusicDownloader#6]
建议调用[eyeD3模块](https://pypi.org/project/eyed3/) 修改无元数据的mp3文件
利用meting api返回的pic id等参数获取歌曲封面，作者名称，专辑名等元数据

另：cookies如果是自己的账号，建议不要漏了

**Comment by Beadd** [comment]
> 建议调用[eyeD3模块](https://pypi.org/project/eyed3/) 修改无元数据的mp3文件 利用meting api返回的pic id等参数获取歌曲封面，作者名称，专辑名等元数据
> 
> 另：cookies如果是自己的账号，建议不要漏了

会去关注的,cookies是未登录游客的,没有就调用不了网易云API

**Comment by Beadd** [comment]
> 建议调用[eyeD3模块](https://pypi.org/project/eyed3/) 修改无元数据的mp3文件 利用meting api返回的pic id等参数获取歌曲封面，作者名称，专辑名等元数据
> 
> 另：cookies如果是自己的账号，建议不要漏了

添加了,但eyeD3我没找到给歌曲添加图片的选项

**Comment by Beadd** [comment]
更新的很晚,一直在学校,难受碰不到电脑

**Comment by htname** [comment]
https://eyed3.readthedocs.io/en/latest/_modules/eyed3/id3/tag.html?highlight=image#
![Screenshot_2022-06-13-18-25-49-26_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/59814884/173334139-3a3603e4-37fa-4949-8d19-e44c39732640.jpg)
![Screenshot_2022-06-13-18-25-30-01_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/59814884/173334148-418feb42-88ca-4f66-8637-964f4655e009.jpg)
![Screenshot_2022-06-13-18-29-54-69_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/59814884/173335046-56b04c68-1e3d-44a6-9699-2b140f1a891e.jpg)
方法如上，思路可以是下载图片文件后存储

**Comment by Beadd** [comment]
> https://eyed3.readthedocs.io/en/latest/_modules/eyed3/id3/tag.html?highlight=image# ![Screenshot_2022-06-13-18-25-49-26_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/59814884/173334139-3a3603e4-37fa-4949-8d19-e44c39732640.jpg) ![Screenshot_2022-06-13-18-25-30-01_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/59814884/173334148-418feb42-88ca-4f66-8637-964f4655e009.jpg) ![Screenshot_2022-06-13-18-29-54-69_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/59814884/173335046-56b04c68-1e3d-44a6-9699-2b140f1a891e.jpg) 方法如上，思路可以是下载图片文件后存储

非常感谢,已经做出来了,在校原因无法及更

**Comment by htname** [comment]
判断是否存在eyed3模块
```
eyed3exist=True
try:
    import eyed3
except ImportError:
    eyed3exist=False
```
后面
```
if eyed3exist:
```

歌词
```
audiofile.tag.lyrics.set(req_lyric.content.decode("utf8"))
```


我是这样的逻辑
```
        if eyed3exist:
            audiofile = eyed3.load(name_url)
            audiofile.tag.artist = data['artist']
            #API in not have album
            #audiofile.tag.album = data['album']
            audiofile.tag.title = data['name']
            #image
            audio_Image = requests.get(data['pic'])
            if (os.path.exists(MusicDirName) == False):
                os.makedirs(MusicDirName)
            with open(MusicDirName+"/pic.jpg", "wb") as code:
                code.write(audio_Image.content)
            imageDate = open(MusicDirName+"/pic.jpg", "rb").read()
            audiofile.tag.images.set(3, imageDate, "image/jpeg")
            audiofile.tag.lyrics.set(req_lyric.content.decode("utf8"))
            #save alright
            audiofile.tag.save()
            #delete pic
            if (os.path.exists(MusicDirName+"/pic.jpg") != False):
                os.remove("./"+MusicDirName+"/pic.jpg")
        else:
            lrc_Name_Url = LyricDirName + "/" + data1[0]['name'] + ".lrc"
            with open(lrc_Name_Url, "wb") as code:
                code.write(req_lyric.content)
```


## 其他建议
os模块有创建文件夹，删除文件等等操作，可以使用os模块进行，调用命令局限于DOS系统（例如del，清屏命令）。。。

**Comment by Beadd** [comment]
> 判断是否存在eyed3模块
> 
> ```
> eyed3exist=True
> try:
>     import eyed3
> except ImportError:
>     eyed3exist=False
> ```
> 
> 后面
> 
> ```
> if eyed3exist:
> ```
> 
> 歌词
> 
> ```
> audiofile.tag.lyrics.set(req_lyric.text)
> ```
> 
> 我是这样的逻辑
> 
> ```
>         if eyed3exist:
>             audiofile = eyed3.load(name_url)
>             audiofile.tag.artist = data['artist']
>             #API in not have album
>             #audiofile.tag.album = data['album']
>             audiofile.tag.title = data['name']
>             #image
>             audio_Image = requests.get(data['pic'])
>             if (os.path.exists(MusicDirName) == False):
>                 os.makedirs(MusicDirName)
>             with open(MusicDirName+"/pic.jpg", "wb") as code:
>                 code.write(audio_Image.content)
>             imageDate = open(MusicDirName+"/pic.jpg", "rb").read()
>             audiofile.tag.images.set(3, imageDate, "image/jpeg")
>             audiofile.tag.lyrics.set(req_lyric.text)
>             #save alright
>             audiofile.tag.save()
>             #delete pic
>             if (os.path.exists(MusicDirName+"/pic.jpg") != False):
>                 os.remove("./"+MusicDirName+"/pic.jpg")
>         else:
>             lrc_Name_Url = LyricDirName + "/" + data1[0]['name'] + ".lrc"
>             with open(lrc_Name_Url, "wb") as code:
>                 code.write(req_lyric.content)
> ```
> 
> ## 其他建议
> os模块有创建文件夹，删除文件等等操作，可以使用os模块进行，调用命令局限于DOS系统（例如del，清屏命令）。。。

直接上代码真是非常感谢,基本上你列出的我都采用了,见v1.7.感谢你的Issues！
