### ISSUE TITLE
下载歌单大约60首闪退

### ISSUE THREAD

**Issue by fmy1993** [Beadd/MusicDownloader#7]
https://music.163.com/#/my/m/music/playlist?id=7201971650

使用exe程序，不知道什么原因

**Comment by Beadd** [comment]
> https://music.163.com/#/my/m/music/playlist?id=7201971650
> 
> 使用exe程序，不知道什么原因

因为第六十多的那首歌曲没有元元素,导致闪退,现在修复了元元素bug,但你的歌单里的第一百多的歌曲由因为编码问题又再次导致闪退,正在解决中
感谢你的Issues

**Comment by fmy1993** [comment]
感谢大佬

**Comment by Beadd** [comment]
> https://music.163.com/#/my/m/music/playlist?id=7201971650
> 
> 使用exe程序，不知道什么原因

已经解决,见v1.7,因为那首歌曲API返回的是空,eyed3报错.现在设置了错误跳过,已经能完整下载你那歌单上共290首歌曲。

**Comment by jyldcr** [comment]
你好大佬，感谢制作这款软件。
刚才先使用exe的软件，下载中程序停止运行，打开log文件只有前面音乐下载成功的信息，然后我下载了.py文件运行。
[歌单](https://music.163.com/#/playlist?id=2944174721)
exe和python都只能下载前16首，.py报错信息为：
`17 Born a Stranger（slow）Traceback (most recent call last):
  File "E:\xxx\MusicDownloader.py", line 291, in <module>
    if Music() == 0:
  File "D:\xx\MusicDownloader.py", line 104, in Music
    plog(str(num) + ' ' + data['name'],str(num) + ' ' + data['name'])
  File "D:\DownLoads\Music\MusicDownloader.py", line 53, in plog
    log.write(loginfo+"\n")
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 7: illegal multibyte sequence`

**Comment by jyldcr** [comment]
你好大佬，感谢歌制作软件。
刚才先使用exe的软件，下载中程序停止运行，打开log文件只有前面音乐下载成功的信息，然后我下载了.py文件运行。
[歌单链接](https://music.163.com/#/playlist?id=2944174721)
exe和python都只能下载前16首，.py报错信息为：
`17 Born a Stranger（slow）Traceback (most recent call last): 
     File "E:\xxx\MusicDownloader.py", line 291, in <module> 
            if Music() == 0: 
     File "E:\xx\MusicDownloader.py", line 104, in Music 
            plog(str(num) + ' ' + data['name'],str(num) + ' ' + data['name']) 
     File "E:\xxx\MusicDownloader.py", line 53, in plog 
            log.write(loginfo+"\n") 
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 7: illegal multibyte sequence`

**Comment by jyldcr** [comment]
你好大佬，感谢制作软件。
刚才先使用exe的软件，下载中程序停止运行，打开log文件只有前面音乐下载成功的信息，然后下载了.py文件运行。
[歌单链接](https://music.163.com/#/playlist?id=2944174721)
.exe和.py文件都只能下载前16首，.py报错信息为：
`17 Born a Stranger（slow）Traceback (most recent call last): `
`     File "E:\xxx\MusicDownloader.py", line 291, in <module>  `
`           if Music() == 0: `
`     File "E:\xxx\MusicDownloader.py", line 104, in Music `
`            plog(str(num) + ' ' + data['name'],str(num) + ' ' + data['name']) `
`     File "E:\xxx\MusicDownloader.py", line 53, in plog `
`            log.write(loginfo+"\n") `
`UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 7: illegal multibyte sequence`
